sonar.projectKey=translationAPI
sonar.projectName=Translation App
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=app.py

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8